### ISSUE TITLE
compile error!

### ISSUE THREAD

**Issue by lincoln310** [workswithweb/MQTTBox#50]
I try to compile it using branch master, but there are some errors here.
node_modules/require-dir/index.js:97
            if (!require.extensions.hasOwnProperty(ext)) {
                                    ^

TypeError: require.extensions.hasOwnProperty is not a function
    at requireDir (node_modules/require-dir/index.js:97:37)
    at Object.<anonymous> (gulpfile.js:16:1)
    at Module._compile (internal/modules/cjs/loader.js:1139:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
    at Module.load (internal/modules/cjs/loader.js:988:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at execute (/usr/local/lib/node_modules/gulp/node_modules/_gulp-cli@2.2.1@gulp-cli/lib/versioned/^3.7.0/index.js:28:18)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/node_modules/_gulp-cli@2.2.1@gulp-cli/index.js:206:24)

**Comment by sathyavikram** [comment]
Its been long time I worked on this project. I think lot of libraries need to be updated.
