### ISSUE TITLE
ypeError: require.extensions.hasOwnProperty is not a function

### ISSUE THREAD

**Issue by czqinyes** [workswithweb/MQTTBox#53]
`TypeError: require.extensions.hasOwnProperty is not a function
    at requireDir (F:\chenzaoqin\project\Study\MQTTBox-master\node_modules\require-dir\index.js:97:37)
    at Object.<anonymous> (F:\chenzaoqin\project\Study\MQTTBox-master\gulpfile.js:16:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at requireOrImport (C:\Users\Administrator\AppData\Roaming\npm\node_modules\gulp\node_modules\gulp-cli\lib\shared\require-or-import.js:19:11)`

Error while gulp, comment line will ok.
`            // if (!require.extensions.hasOwnProperty(ext)) {
           //     continue;
           // }
`

**Comment by HuangNO1** [comment]
the line is at `MQTTBox/node_modules/require-dir/index.js` : 97
